<head>	
		<html lang="en">
		<meta name="description" content="Western Massachusetts Children's Nature Exploration Project. Images of nature, rocks, mountains, clouds, leaves, trees, fungi, shadows, and
		other things" />
		<meta name="keywords" content="Western Massachusetts Children's Nature Exploration Project. Images of mountains, rocks, trees, leaves, faces, clouds, fungi, shadows, snow. Nature
		facts. Oak trees. Shadows. Clouds. Snow." />
		<meta name="author" content="Laurie Addoms">
		<!--meta name="google-site-verification" content="SgSoecd7wlU8s7ZpugWhIgYAJd5VMNL3RKI4zTEtUl8" /-->
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta name=viewport content="width=device-width, initial-scale=1">
		<link href="https://fonts.googleapis.com/css?family=Marck+Script" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Kalam" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
		<meta http-equiv="content-type" content="text/html;charset=uts-8" />
		<title>Western Massachusetts Children's Nature Exploration Project</title>
		<link rel="stylesheet" type="text/css" href="slick/slick.css"/>
		<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    	<link href="styling.css" type="text/css" rel="stylesheet" />
</head>